// flow-typed signature: 35de8102c74da08cd8dbca28c68f2234
// flow-typed version: <<STUB>>/exponent_v^14.0.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'exponent'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'exponent' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'exponent/src/__tests__/Notifications-tests' {
  declare module.exports: any;
}

declare module 'exponent/src/Accelerometer' {
  declare module.exports: any;
}

declare module 'exponent/src/apisAreAvailable' {
  declare module.exports: any;
}

declare module 'exponent/src/Asset' {
  declare module.exports: any;
}

declare module 'exponent/src/Audio' {
  declare module.exports: any;
}

declare module 'exponent/src/Components/AppLoading.android' {
  declare module.exports: any;
}

declare module 'exponent/src/Components/AppLoading.ios' {
  declare module.exports: any;
}

declare module 'exponent/src/Components/BarCodeScanner' {
  declare module.exports: any;
}

declare module 'exponent/src/Components/BlurView.android' {
  declare module.exports: any;
}

declare module 'exponent/src/Components/BlurView.ios' {
  declare module.exports: any;
}

declare module 'exponent/src/Components/index' {
  declare module.exports: any;
}

declare module 'exponent/src/Components/KeepAwake' {
  declare module.exports: any;
}

declare module 'exponent/src/Components/LinearGradient.android' {
  declare module.exports: any;
}

declare module 'exponent/src/Components/LinearGradient.ios' {
  declare module.exports: any;
}

declare module 'exponent/src/Components/Video' {
  declare module.exports: any;
}

declare module 'exponent/src/Constants' {
  declare module.exports: any;
}

declare module 'exponent/src/Contacts' {
  declare module.exports: any;
}

declare module 'exponent/src/createTHREEViewClass' {
  declare module.exports: any;
}

declare module 'exponent/src/DangerZone' {
  declare module.exports: any;
}

declare module 'exponent/src/Exponent' {
  declare module.exports: any;
}

declare module 'exponent/src/Font' {
  declare module.exports: any;
}

declare module 'exponent/src/GLView' {
  declare module.exports: any;
}

declare module 'exponent/src/Google' {
  declare module.exports: any;
}

declare module 'exponent/src/Gyroscope' {
  declare module.exports: any;
}

declare module 'exponent/src/ImagePicker' {
  declare module.exports: any;
}

declare module 'exponent/src/lib/createSensorWrapper' {
  declare module.exports: any;
}

declare module 'exponent/src/lib/Queue' {
  declare module.exports: any;
}

declare module 'exponent/src/Location' {
  declare module.exports: any;
}

declare module 'exponent/src/Logs' {
  declare module.exports: any;
}

declare module 'exponent/src/Notifications' {
  declare module.exports: any;
}

declare module 'exponent/src/Permissions' {
  declare module.exports: any;
}

declare module 'exponent/src/registerRootComponent' {
  declare module.exports: any;
}

declare module 'exponent/src/takeSnapshotAsync' {
  declare module.exports: any;
}

declare module 'exponent/tools/hashAssetFiles' {
  declare module.exports: any;
}

// Filename aliases
declare module 'exponent/src/__tests__/Notifications-tests.js' {
  declare module.exports: $Exports<'exponent/src/__tests__/Notifications-tests'>;
}
declare module 'exponent/src/Accelerometer.js' {
  declare module.exports: $Exports<'exponent/src/Accelerometer'>;
}
declare module 'exponent/src/apisAreAvailable.js' {
  declare module.exports: $Exports<'exponent/src/apisAreAvailable'>;
}
declare module 'exponent/src/Asset.js' {
  declare module.exports: $Exports<'exponent/src/Asset'>;
}
declare module 'exponent/src/Audio.js' {
  declare module.exports: $Exports<'exponent/src/Audio'>;
}
declare module 'exponent/src/Components/AppLoading.android.js' {
  declare module.exports: $Exports<'exponent/src/Components/AppLoading.android'>;
}
declare module 'exponent/src/Components/AppLoading.ios.js' {
  declare module.exports: $Exports<'exponent/src/Components/AppLoading.ios'>;
}
declare module 'exponent/src/Components/BarCodeScanner.js' {
  declare module.exports: $Exports<'exponent/src/Components/BarCodeScanner'>;
}
declare module 'exponent/src/Components/BlurView.android.js' {
  declare module.exports: $Exports<'exponent/src/Components/BlurView.android'>;
}
declare module 'exponent/src/Components/BlurView.ios.js' {
  declare module.exports: $Exports<'exponent/src/Components/BlurView.ios'>;
}
declare module 'exponent/src/Components/index.js' {
  declare module.exports: $Exports<'exponent/src/Components/index'>;
}
declare module 'exponent/src/Components/KeepAwake.js' {
  declare module.exports: $Exports<'exponent/src/Components/KeepAwake'>;
}
declare module 'exponent/src/Components/LinearGradient.android.js' {
  declare module.exports: $Exports<'exponent/src/Components/LinearGradient.android'>;
}
declare module 'exponent/src/Components/LinearGradient.ios.js' {
  declare module.exports: $Exports<'exponent/src/Components/LinearGradient.ios'>;
}
declare module 'exponent/src/Components/Video.js' {
  declare module.exports: $Exports<'exponent/src/Components/Video'>;
}
declare module 'exponent/src/Constants.js' {
  declare module.exports: $Exports<'exponent/src/Constants'>;
}
declare module 'exponent/src/Contacts.js' {
  declare module.exports: $Exports<'exponent/src/Contacts'>;
}
declare module 'exponent/src/createTHREEViewClass.js' {
  declare module.exports: $Exports<'exponent/src/createTHREEViewClass'>;
}
declare module 'exponent/src/DangerZone.js' {
  declare module.exports: $Exports<'exponent/src/DangerZone'>;
}
declare module 'exponent/src/Exponent.js' {
  declare module.exports: $Exports<'exponent/src/Exponent'>;
}
declare module 'exponent/src/Font.js' {
  declare module.exports: $Exports<'exponent/src/Font'>;
}
declare module 'exponent/src/GLView.js' {
  declare module.exports: $Exports<'exponent/src/GLView'>;
}
declare module 'exponent/src/Google.js' {
  declare module.exports: $Exports<'exponent/src/Google'>;
}
declare module 'exponent/src/Gyroscope.js' {
  declare module.exports: $Exports<'exponent/src/Gyroscope'>;
}
declare module 'exponent/src/ImagePicker.js' {
  declare module.exports: $Exports<'exponent/src/ImagePicker'>;
}
declare module 'exponent/src/lib/createSensorWrapper.js' {
  declare module.exports: $Exports<'exponent/src/lib/createSensorWrapper'>;
}
declare module 'exponent/src/lib/Queue.js' {
  declare module.exports: $Exports<'exponent/src/lib/Queue'>;
}
declare module 'exponent/src/Location.js' {
  declare module.exports: $Exports<'exponent/src/Location'>;
}
declare module 'exponent/src/Logs.js' {
  declare module.exports: $Exports<'exponent/src/Logs'>;
}
declare module 'exponent/src/Notifications.js' {
  declare module.exports: $Exports<'exponent/src/Notifications'>;
}
declare module 'exponent/src/Permissions.js' {
  declare module.exports: $Exports<'exponent/src/Permissions'>;
}
declare module 'exponent/src/registerRootComponent.js' {
  declare module.exports: $Exports<'exponent/src/registerRootComponent'>;
}
declare module 'exponent/src/takeSnapshotAsync.js' {
  declare module.exports: $Exports<'exponent/src/takeSnapshotAsync'>;
}
declare module 'exponent/tools/hashAssetFiles.js' {
  declare module.exports: $Exports<'exponent/tools/hashAssetFiles'>;
}
