// flow-typed signature: 977e2f833500def8b1d3eede0126f85b
// flow-typed version: <<STUB>>/react-native-calendar-reminders_v1.0.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-calendar-reminders'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-calendar-reminders' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-calendar-reminders/index.android' {
  declare module.exports: any;
}

declare module 'react-native-calendar-reminders/index.ios' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-calendar-reminders/index.android.js' {
  declare module.exports: $Exports<'react-native-calendar-reminders/index.android'>;
}
declare module 'react-native-calendar-reminders/index.ios.js' {
  declare module.exports: $Exports<'react-native-calendar-reminders/index.ios'>;
}
