// flow-typed signature: 4a8e2c1903a0849c930926190255a6a9
// flow-typed version: <<STUB>>/@exponent/vector-icons_v~4.0.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@exponent/vector-icons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@exponent/vector-icons' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@exponent/vector-icons/createIconSet' {
  declare module.exports: any;
}

declare module '@exponent/vector-icons/createIconSetFromFontello' {
  declare module.exports: any;
}

declare module '@exponent/vector-icons/createIconSetFromIcoMoon' {
  declare module.exports: any;
}

declare module '@exponent/vector-icons/Entypo' {
  declare module.exports: any;
}

declare module '@exponent/vector-icons/EvilIcons' {
  declare module.exports: any;
}

declare module '@exponent/vector-icons/FontAwesome' {
  declare module.exports: any;
}

declare module '@exponent/vector-icons/Foundation' {
  declare module.exports: any;
}

declare module '@exponent/vector-icons/iconFontSources' {
  declare module.exports: any;
}

declare module '@exponent/vector-icons/Ionicons' {
  declare module.exports: any;
}

declare module '@exponent/vector-icons/MaterialCommunityIcons' {
  declare module.exports: any;
}

declare module '@exponent/vector-icons/MaterialIcons' {
  declare module.exports: any;
}

declare module '@exponent/vector-icons/Octicons' {
  declare module.exports: any;
}

declare module '@exponent/vector-icons/SimpleLineIcons' {
  declare module.exports: any;
}

declare module '@exponent/vector-icons/website/src/App' {
  declare module.exports: any;
}

declare module '@exponent/vector-icons/website/src/index' {
  declare module.exports: any;
}

declare module '@exponent/vector-icons/Zocial' {
  declare module.exports: any;
}

// Filename aliases
declare module '@exponent/vector-icons/createIconSet.js' {
  declare module.exports: $Exports<'@exponent/vector-icons/createIconSet'>;
}
declare module '@exponent/vector-icons/createIconSetFromFontello.js' {
  declare module.exports: $Exports<'@exponent/vector-icons/createIconSetFromFontello'>;
}
declare module '@exponent/vector-icons/createIconSetFromIcoMoon.js' {
  declare module.exports: $Exports<'@exponent/vector-icons/createIconSetFromIcoMoon'>;
}
declare module '@exponent/vector-icons/Entypo.js' {
  declare module.exports: $Exports<'@exponent/vector-icons/Entypo'>;
}
declare module '@exponent/vector-icons/EvilIcons.js' {
  declare module.exports: $Exports<'@exponent/vector-icons/EvilIcons'>;
}
declare module '@exponent/vector-icons/FontAwesome.js' {
  declare module.exports: $Exports<'@exponent/vector-icons/FontAwesome'>;
}
declare module '@exponent/vector-icons/Foundation.js' {
  declare module.exports: $Exports<'@exponent/vector-icons/Foundation'>;
}
declare module '@exponent/vector-icons/iconFontSources.js' {
  declare module.exports: $Exports<'@exponent/vector-icons/iconFontSources'>;
}
declare module '@exponent/vector-icons/index' {
  declare module.exports: $Exports<'@exponent/vector-icons'>;
}
declare module '@exponent/vector-icons/index.js' {
  declare module.exports: $Exports<'@exponent/vector-icons'>;
}
declare module '@exponent/vector-icons/Ionicons.js' {
  declare module.exports: $Exports<'@exponent/vector-icons/Ionicons'>;
}
declare module '@exponent/vector-icons/MaterialCommunityIcons.js' {
  declare module.exports: $Exports<'@exponent/vector-icons/MaterialCommunityIcons'>;
}
declare module '@exponent/vector-icons/MaterialIcons.js' {
  declare module.exports: $Exports<'@exponent/vector-icons/MaterialIcons'>;
}
declare module '@exponent/vector-icons/Octicons.js' {
  declare module.exports: $Exports<'@exponent/vector-icons/Octicons'>;
}
declare module '@exponent/vector-icons/SimpleLineIcons.js' {
  declare module.exports: $Exports<'@exponent/vector-icons/SimpleLineIcons'>;
}
declare module '@exponent/vector-icons/website/src/App.js' {
  declare module.exports: $Exports<'@exponent/vector-icons/website/src/App'>;
}
declare module '@exponent/vector-icons/website/src/index.js' {
  declare module.exports: $Exports<'@exponent/vector-icons/website/src/index'>;
}
declare module '@exponent/vector-icons/Zocial.js' {
  declare module.exports: $Exports<'@exponent/vector-icons/Zocial'>;
}
